export const MATCH_CONSTANTS = {
  // === 投球 ===
  FASTBALL_BASE_RATIO: 0.40,
  STRIKE_ZONE_TARGET_BASE: 0.745,
  CONTROL_ERROR_SCALE: 2.0,

  // === 打撃 ===
  BASE_CONTACT_RATE: 0.85,
  BREAK_CONTACT_PENALTY: 0.03,   // was 0.04: 変化球ペナルティ緩和
  VELOCITY_CONTACT_PENALTY: 0.0015,
  FAIR_BASE_RATE: 0.54,
  TECHNIQUE_FAIR_BONUS: 0.15,    // was 0.25

  // === 打球 ===
  HOME_RUN_DISTANCE: 90,         // was 100: HRハードル下げ
  FLY_MAX_DISTANCE: 130,

  // === 守備 ===
  FLY_CATCH_BASE: 0.85,
  GROUND_OUT_BASE: 0.60,
  DOUBLE_PLAY_BASE: 0.25,        // was 0.30
  ERROR_POPUP_RATE: 0.03,        // was 0.05

  // === 投手スタミナ ===
  STAMINA_PER_PITCH_BASE: 1.0,
  STAMINA_VELOCITY_LOW: 0.85,
  STAMINA_BREAK_LOW: 0.70,

  // === 自信 ===
  CONFIDENCE_HIT_GAIN: 10,
  CONFIDENCE_HR_GAIN: 20,
  CONFIDENCE_WALK_GAIN: 5,
  CONFIDENCE_STRIKEOUT_LOSS: -8,
  CONFIDENCE_POPUP_LOSS: -3,
  CONFIDENCE_DP_LOSS: -10,
  CONFIDENCE_CLUTCH_FAIL_LOSS: -12,

  CONFIDENCE_PITCHER_K_GAIN: 5,
  CONFIDENCE_PITCHER_OUT_GAIN: 2,
  CONFIDENCE_PITCHER_HIT_LOSS: -5,
  CONFIDENCE_PITCHER_HR_LOSS: -15,
  CONFIDENCE_PITCHER_WALK_LOSS: -8,
  CONFIDENCE_PITCHER_CLEAN_INNING: 8,

  // === プレッシャー ===
  PRESSURE_SCORING_POS: 20,
  PRESSURE_CLOSE_GAME: 15,
  PRESSURE_LATE_INNING: 10,
  PRESSURE_NINTH: 20,
  PRESSURE_KOSHIEN: 15,
  PRESSURE_BASES_LOADED: 10,

  // === サイン ===
  SIGN_COMPLIANCE_BASE: 0.90,

  // === 試合設定 ===
  DEFAULT_INNINGS: 9,
  DEFAULT_MAX_EXTRAS: 3,
  MOUND_VISIT_LIMIT: 3,
  MOUND_VISIT_CONFIDENCE_GAIN: 15,

  // === HBP ===
  HIT_BY_PITCH_BASE_RATE: 0.008,
} as const;
