/**
 * アプリケーションバージョン情報
 *
 * ルール:
 * - VERSION: semver `Major.Minor.Patch`
 *   - Major: 大きな構造変更・Phase 完了等
 *   - Minor: 機能追加 (feat コミット)
 *   - Patch: バグ修正 (fix コミット)
 * - **毎デプロイ必ず VERSION を上げる**（高橋さん指示 2026-04-19）
 * - BUILD_DATE / GIT_SHA はビルド時に scripts/bump-version.mjs が自動埋め込み
 *
 * 更新手順:
 *   1. CHANGELOG に新エントリを追加
 *   2. VERSION を bump
 *   3. `npm run bump` を実行（BUILD_DATE / GIT_SHA を更新）
 *   4. デプロイ
 */

export const VERSION = '0.37.0';

// ↓↓↓ AUTO-GENERATED: scripts/bump-version.mjs が書き換えます（手動編集不可）↓↓↓
export const BUILD_DATE = '2026-04-23 14:41 UTC';
export const GIT_SHA = 'dcaefab-dirty';
// ↑↑↑ AUTO-GENERATED END ↑↑↑

export interface ChangelogEntry {
  version: string;
  date: string;
  changes: string[];
}

/**
 * 新しいバージョンは先頭に追加する (最新が一番上)
 */
export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '0.37.0',
    date: '2026-04-23',
    changes: [
      '🏏 v0.37.0: 打球シミュレーション本格化（高橋さん指示）',
      '  🎯 [1] 打球方向を打者の左右・コース・タイミングで決定',
      '    従来: rng.gaussian(45, 15-30) でセンター集中のみ → 外野フライがほぼ出ない',
      '    改訂: コース別の想定方向 + タイミング偏差 + 打者の左右で反転',
      '      - 右打者のインコース → 引っ張り (direction ≈ 20°, レフト方向)',
      '      - 右打者のアウトコース → 流し (direction ≈ 70°, ライト方向)',
      '      - ど真ん中 → センター',
      '      - 左打者は全て左右反転',
      '    technique が高いほど σ 小で狙い通り',
      '  ⚡ [2] スイングタイミング (early/perfect/late) 判定',
      '    - 速球 (>145km/h) → 振り遅れ (late) しやすい',
      '    - 緩い球 (<115km/h チェンジアップ) → 早打ち (early) しやすい',
      '    - インコース速球 → 詰まり (early)',
      '    - アウトコース速球 → 流し気味 (late)',
      '    - ゾーン外 → タイミングずれやすい',
      '    - contact + technique が高いほど perfect 率 UP',
      '    タイミングずれると:',
      '      - 打球速度 -20〜25%',
      '      - 飛距離 -15%',
      '      - ゴロ/ポップアップ増',
      '      - 方向が 18° ずれる (早打ち=引っ張り側、振り遅れ=流し側)',
      '  🏁 [3] ファール判定を自然な打球方向から',
      '    従来: swing-result.ts で一律 10% の確率＋ランダム方向 → 同じ場所に集中',
      '    改訂: bat-contact 内で direction が極端 (<-10° or >100°) ならファール確定',
      '      - 際どい方向 (-10〜0°, 90〜100°) は 70% ファール',
      '      - ライン際 (0〜5°, 85〜90°) は 25% ファール',
      '    2ストライク時は +10% ファール率（粘り）',
      '    ファール方向: 三塁側 (-30〜-2°) または 一塁側 (92〜120°)',
      '  🧪 [4] bat-contact.test.ts に検証テスト 4件追加',
      '    右/左打者の引っ張り、右打アウトコース流し、チェンジアップ早打ち',
      '    全48テスト pass (既存43 + 新規5)',
    ],
  },
  {
    version: '0.36.0',
    date: '2026-04-23',
    changes: [
      '🎬 v0.36.0: ホームラン演出・ファール軌道 3件修正（高橋さん指示）',
      '  💥 [1] ホームラン打球速度を遅く',
      '    打球durationを speed=bullet 固定(500ms) → 2400ms に変更',
      '    スタンドまで飛ぶ距離に見合った時間でゆっくり弧を描く',
      '    peakHeightNorm を 0.8 → 1.4 に増やして高く舞い上がる演出',
      '  🏃 [2] ホームラン時に外野手が追走',
      '    buildHomeRunSequence() 新規 — flyBall + fielderMove + batterRun',
      '    外野手は打球方向へ全力で走るがフェンス前で止まる（追いつかない演出）',
      '    fielderMove.noCatch=true フラグで「捕球しない」動作を実現',
      '    バッターも一塁へ走り出す',
      '  ⚾ [3] ファールの軌道表示',
      '    swing-result.ts: ファール時も batContact を生成（direction を -25°〜-5° or 95°〜115° にずらす）',
      '    process-pitch.ts: pitchResult.foulContact に打球情報を載せる',
      '    match-store.ts: foulContact を pitchLog の batContact 形式に合流（fieldResult.type=foul）',
      '    page.tsx: isFoul 分岐で triggerHitAnimation のみ実行（外野手は動かず打球だけ描画）',
      '    飛距離は元の 50〜80%、方向はファールゾーン内',
    ],
  },
  {
    version: '0.35.0',
    date: '2026-04-23',
    changes: [
      '🎬 v0.35.0: 試合演出・物理感 4件修正（高橋さん指示）',
      '  💥 [1] ホームラン判定を fieldResult.type 優先に変更',
      '    エンジンが home_run を返した場合、contactType が ground_ball でも fly_ball 扱いで打球軌跡を生成',
      '    distance を 380 以上に補正して場外までしっかり飛ばす',
      '    速度も bullet 固定で爽快感 UP',
      '  🔄 [2] CHANGE 帯演出を追加',
      '    PLAYBALL と同じ帯デザインで「CHANGE」文字＋次イニング表記を表示',
      '    3アウト後にスコアボードが即表示されてしまう問題を解消',
      '    useScoreboardVisibility に changeDelayMs (デフォルト 1500ms) 追加',
      '    CHANGE 帯 → 1.5秒後 → スコアボードの順序で演出',
      '  ⚾ [3] チェンジアップ速度を本格的に遅く',
      '    選球種係数を導入 (fastball=1.0 / cutter=0.95 / sinker=0.92 / slider=0.85 / fork=0.85 / curve=0.80 / changeup=0.68)',
      '    チェンジアップは全球種で最も遅い (ストレート比 -32%)',
      '  💨 [4] 球速差の視覚的拡大',
      '    pitchSpeedToDuration 範囲を 450-200ms → 550-130ms に拡大 (差 420ms、3.7倍)',
      '    100km/h と 150km/h の体感差が明確に',
      '  📝 [5] 配球学習ロジック (質問)',
      '    現状: 各投球は単発で処理され、前球の影響は未実装',
      '    インコース→アウトコースの打ちづらさ、高めの被弾率向上などは未反映',
      '    別リリースでの実装を計画（要大きな engine 変更）',
    ],
  },
  {
    version: '0.34.0',
    date: '2026-04-23',
    changes: [
      '🔊 v0.34.0: 効果音システム導入（高橋さん要望）',
      '  🎵 AI 生成サウンド 12 種（elevenlabs/sound-effects）',
      '    バット金属音 5段階（弱い当たり〜完璧な芯食い）',
      '    バント音 1種',
      '    投球音 1種（シュッ）',
      '    キャッチャー捕球音 5段階（球速 110km/h未満〜150km/h以上）',
      '  🧩 src/ui/sound/useSound.ts 新規作成',
      '    HTML5 Audio で実装、LocalStorage で音量・ミュート永続化',
      '    hitContactToBatSoundId(): 打球強度 + 打球種別から音レベル算出',
      '    pitchSpeedToCatchSoundId(): 球速から捕球音レベル算出',
      '  🎚️ SoundControl コンポーネント追加（画面右上固定）',
      '    🔊 アイコン → ポップオーバーで音量スライダー + ミュートボタン',
      '  🔁 再生タイミング',
      '    投球音: 投球アニメ開始と同時',
      '    捕球音: ストライク/ボール判定時（打球・ファウル除外）、球速に応じた遅延',
      '    打球音: バットコンタクト時、投球から少し遅れて再生',
      '  📁 サウンドファイル: public/sounds/generated/ 配下（差し替え可）',
    ],
  },
  {
    version: '0.33.0',
    date: '2026-04-23',
    changes: [
      '✨ v0.33.0: アナリスト分析 UI 改善 3件（高橋さん指示）',
      '  📝 [1] アナリスト分析の主語を明確化',
      '    コメント文頭に「相手投手◯◯は」を付与し、投手のことか打者のことか一目瞭然に',
      '    generateAnalystComment() / generateAnalystCommentFromManagers() に pitcherName 引数追加',
      '    match-store の addAnalystComment も pitcherName を受け取り、page.tsx から view.pitcher.name を渡す',
      '  📋 [2] アナリスト分析を「選手心理」パネルにタブ格納',
      '    PsycheWindow に tabHeader を追加し「🧠 選手心理」と「📊 アナリスト分析」を切替',
      '    心理タブ選択中のみバブルローテーションを実行（CPU 節約）',
      '    タブ選択と同時に markAnalystRead() で既読化',
      '  🔔 [3] 新着バッジ表示（未読件数）',
      '    match-store に lastReadAnalystId 追加（persist 対象）',
      '    最新 analystComment.id !== lastReadAnalystId なら未読＝バッジ "1" 表示（赤丸＋脈動アニメ）',
      '    アナリストタブを開いた瞬間に lastReadAnalystId を更新して既読化',
    ],
  },
  {
    version: '0.32.5',
    date: '2026-04-23',
    changes: [
      '🐛 Phase 12-M/hotfix-5.1: 前版の UI 修正が不完全だったため再修正',
      '  🎨 BSO カウント表示を MatchHUD (グラウンド左上オーバーレイ) に適用',
      '    ※ v0.32.4 は scoreboard 内のみ修正で、実際に高橋さんが見ている HUD は旧表示のままだった',
      '  📐 緑のフィールド(内野+外野)自体を拡大',
      '    FIELD_MAX_RADIUS_FT 400 → 325、getPxPerFoot 分母 800 → 650',
      '    ballparkContainer サイズは元の 270px に戻し、canvas 内の緑描画だけが大きくなる',
    ],
  },
  {
    version: '0.32.4',
    date: '2026-04-23',
    changes: [
      '✨ Phase 12-M/hotfix-5: UI仕様修正3件（+ 長打アニメは次版）',
      '  🎨 BSO カウント表示を実物のカウンター模倣に変更',
      '    B: 緑3個 / S: 黄2個 / O: 赤2個 のドット表示',
      '  📐 グラウンドを拡大 270px → 420px（左上カウンターまで大きく）',
      '  ⚡ ピンチ・投手疲労・クロスゲームでの自動停止を解除',
      '    → チャンス時のみ停止（自校攻撃中の采配を促すため）',
      '  🚧 長打・タッチアップアニメは次版 (0.32.5) で実装予定',
    ],
  },
  {
    version: '0.32.3',
    date: '2026-04-23',
    changes: [
      '✨ Phase 12-M/hotfix-4: 詳細采配の継続表示を明確化',
      '  📋 采配パネル上部に「継続中の詳細采配」バッジを追加',
      '  📝 「そのまま」ボタンのサブラベルを文脈依存に変更',
      '    継続中あり → 「前回の指示を継続」',
      '    継続中なし → 「サインなし」',
      '  (挙動は変えず、UI の明確化のみ。打者交代まで詳細采配は維持される仕様)',
    ],
  },
  {
    version: '0.32.2',
    date: '2026-04-23',
    changes: [
      '🐛 Phase 12-M/hotfix-3: 学校短縮名表示 + アナリスト上書き方式',
      '  🐛 Bug: 試合中の選手名右の (学校短縮名) が一部表示されない',
      '    → matchProjector / match-store に teamShortName() fallback を追加',
      '    → shortName 欠損セーブでも name から自動生成して表示',
      '  ✨ アナリスト分析を「随時上書き」方式に変更（最新 1 件のみ保持）',
    ],
  },
  {
    version: '0.32.1',
    date: '2026-04-23',
    changes: [
      '🐛 Phase 12-M/hotfix-2: アニメーション停止 + アナリスト未動作バグ修正',
      '  🐛 Bug: 2回表からアニメーションが止まる（pitchLog 50件 cap）',
      '    → pitchLog.length 依存を pitchLog (reference equality) に変更',
      '    → lastProcessedPitchRef で同一エントリへの再発火防止',
      '  🐛 Bug: アナリスト分析が機能しない（PauseReason に inning_end が存在しない）',
      '    → pitchLog の inning/half 切替を検出してコメント生成するように修正',
    ],
  },
  {
    version: '0.32.0',
    date: '2026-04-23',
    changes: [
      '✅ Phase 12-M: Bug #1-2 修正 + Feature #3-4 実装',
      '  🐛 Bug #1: 夏大会で「試合へ進む」ボタンが出ない → pendingInteractiveMatch auto-sim 防止で修正',
      '  🐛 Bug #2: 試合中断時に夏大会が終わらない → stale activeTournament 削除 + phase 遷移で修正',
      '  ✨ Feature #3: ホーム画面に練習メニュー常時表示',
      '  ✨ Feature #4: ニュース画面で選手詳細表示可能',
      '  🐛 Bug #5 (hotfix): 3回表からアニメーション停止 → useEffect dependency を空配列に修正',
      '📝 新規テスト: interactive-match-bug12m.test.ts (store-level regression test)',
    ],
  },
  {
    version: '0.31.0',
    date: '2026-04-23',
    changes: [
      '🐛 Phase 12-L: バグ修正4件 + アナリスト心理統合',
      '',
      '【バグ1】秋大会が「1週間進む」で発動しないことがある（回帰テスト追加）',
      '  tests/stores/autumn-tournament-e2e.test.ts: advanceWeek連続押しの回帰テスト追加',
      '  既存の world-ticker.ts の isAutumnWindow 修正は維持、テストで担保',
      '',
      '【バグ2】試合中にアニメーションが止まる',
      '  useBallAnimation.ts: triggerPitchAnimation/triggerHitAnimation/triggerPlaySequence の',
      '  各トリガー開始時に他の全RAF（rafRef/homeRunRafRef/seqRafRef）を停止するよう修正',
      '  mountedRef を追加してアンマウント後の setBallState 呼び出しを防止',
      '',
      '【バグ3】ストライクゾーン内角・外角が左打者で反転しない',
      '  buildNarration.ts: pitchLocationJPForBatter() を新規追加',
      '  左打者（battingSide=left）の場合にのみ内角・外角テキストをミラー反転',
      '  ストライクゾーン描画（投手視点）は変更なし、ナレーションテキストのみ対応',
      '',
      '【バグ4】試合読み込み中で止まることがある',
      '  match-store.ts: onRehydrateStorage の state=null 時も _hasHydrated=true をセット',
      '  match-store.ts: localStorage 破損時に localStorage.removeItem() で自動クリア',
      '  page.tsx: matchStore hydration タイムアウト 3秒 を追加',
      '',
      '【機能】アナリスト解析コメントを心理ウィンドウに統合表示',
      '  PsycheWindow.tsx: analystComments / hasAnalyst props を追加',
      '  AnalystSection コンポーネントをPsycheWindow内部に統合',
      '  psycheWindow.module.css: analystSection 系スタイルを追加',
      '  page.tsx: PsycheWindow に analystComments/hasAnalyst を渡すよう変更',
    ],
  },
  {
    version: '0.30.0',
    date: '2026-04-23',
    changes: [
      '⚾ Phase 12-K: 選手心理延長・アナリスト分析・アニメーション修正',
      '',
      '【タスク1】選手心理ウィンドウのローテーション延長',
      '  PsycheWindow.tsx: ローテーション間隔 1秒 → 2秒に延長（視認性向上）',
      '  psycheWindow.module.css: フェードアニメーション 0.2s → 0.3s に拡大',
      '  ローテーション位置インジケーター（ドット）の挙動は変更なし',
      '',
      '【タスク2】アナリストマネージャーによる相手投手分析コメント',
      '  新規: src/engine/staff/analyst.ts — 投球ログ集計・分析ロジック',
      '    generateAnalystComment(): マネージャーレベルに応じたコメント生成',
      '    generateAnalystCommentFromManagers(): マネージャーリストから最高レベルを選択',
      '    分析対象: 球種傾向・コース傾向・カウント別配球・ランナー時傾向',
      '    レベル別ノイズ: レベル1=ノイズ多(0.6)〜レベル5=ほぼ正確(0.05)',
      '    1回終了時: 「まだ読み切れません」弱コメント',
      '    2回以降: 球種/コース/カウント/ランナー傾向の本格分析',
      '  新規: src/app/play/match/[matchId]/AnalystPanel.tsx — アナリストパネルUI',
      '    実況ログとは別枠の吹き出し形式コメント表示',
      '    過去のコメントはスクロール可能',
      '    コメント種別アイコン (⚾📍🔢🏃📋❓) 付き',
      '    マネージャーのレベルを★表示',
      '  match-store.ts: analystComments: AnalystComment[] を追加（スキーマ互換）',
      '    addAnalystComment() アクション追加',
      '    persist に analystComments を含める',
      '    initMatch() でリセット',
      '  page.tsx: イニング終了（inning_end）時にアナリストコメントを自動生成',
      '    analytics ロールのマネージャーが存在する場合のみパネル表示',
      '',
      '【タスク3】アニメーション停止バグ修正',
      '  Ballpark.tsx 修正:',
      '    visibilitychange リスナー追加: タブ復帰時にアニメーションループを再起動',
      '    isLoopRunningRef guard: ResizeObserver 発火時のループ二重起動防止',
      '    ballAnimStateRef: ループ内から最新のアニメーション状態を参照できるよう改善',
      '    アンマウント時のクリーンアップを isLoopRunningRef を含めて徹底',
      '',
      '【テスト】',
      '  tests/engine/staff/analyst.test.ts 新規 — 19件',
      '    各レベルのコメント生成・分析の境界値・マネージャー選択ロジック',
      '  tests/ui/match-visual/animation-lifecycle.test.ts 新規 — 18件',
      '    isAnimating 判定ロジック・二重起動防止・visibilitychange 復帰・rehydrate後描画',
    ],
  },
  {
    version: '0.29.0',
    date: '2026-04-23',
    changes: [
      '⚾ Phase 12-J: 打球種類に応じたリアルな守備アニメーション',
      '',
      '【問題】buildGroundOutSequence() が常にゴロ→送球→一塁アウトのパターンで動き、',
      '        実際の pitchResult（ヒット/アウト/フライ等）に関係なく「アウト」表示になっていた。',
      '',
      '【解決】buildPlaySequence(contact) 統一API を新設し、fieldResult.type に基づいて',
      '        適切なシーケンスを自動選択するように変更。',
      '',
      '【新規関数 (useBallAnimation.ts)】',
      '  buildPlaySequence(): 統一API — fieldResultType に基づくシーケンス自動選択',
      '  buildFlyoutSequence(): 外野フライ/ファウルフライアウト',
      '  buildPopupSequence(): 内野ポップアップアウト',
      '  buildHitSequence(): シングルヒット（外野打球→カット→中継）',
      '  buildInfieldHitSequence(): 内野安打（ゴロが抜ける→一塁間に合わず）',
      '  buildDoubleSequence(): 二塁打（打者が一塁→二塁の2段階走塁）',
      '  buildTripleSequence(): 三塁打（打者が一塁→二塁→三塁の3段階走塁）',
      '  buildSacrificeFlySequence(): 犠牲フライ（外野キャッチ→バックホーム）',
      '',
      '【新フェーズ種類】',
      '  flyBall: フライボール軌跡（高い弧、peakHeight パラメータで高さ制御）',
      '  PlaySequenceState.ballHeightNorm: シーケンス中のボール高さを BallparkCanvas に反映',
      '',
      '【BallparkCanvas.ts 更新】',
      '  drawResultFlash(): baseKey（first/second/third/catcher）に応じた表示位置に対応',
      '  ballHeightNorm: シーケンス状態から取得してフライボールの影を正しく描画',
      '',
      '【page.tsx 更新 (match/[matchId])】',
      '  buildGroundOutSequence 直接呼び出し → buildPlaySequence 統一APIへ切り替え',
      '  batContact.fieldResult.type を buildPlaySequence に渡してシーケンスを決定',
      '  ホームランのみ従来通り triggerHitAnimation + triggerHomeRunEffect を維持',
      '',
      '【テスト】tests/ui/match-visual/play-sequences.test.ts 新規追加 — 32 件',
      '  各シーケンス関数のフェーズ構成・テキスト・走塁段階数・後方互換性を検証',
    ],
  },
  {
    version: '0.28.0',
    date: '2026-04-23',
    changes: [
      '⚾ Phase 12-I: 自動進行采配継続・心理ウィンドウ統合・vs表示改行',
      '【I-1】自動進行中の前回采配継続',
      '  consumeNextOrder() が pendingNextOrder=null のとき lastOrder を継続指示として返す',
      '  AutoAdvanceBarの「指示なし」ボタンを「継続中の指示: ○○」表示に変更',
      '  新テスト: 前回采配継続・pendingが優先されること・消費後は継続指示を返すこと',
      '',
      '【I-2】選手心理ウィンドウの統合',
      '  3バブル横並び → 1バブル + 1秒ローテーション表示',
      '  打者→捕手→投手の順で1秒ごとに切り替え（null役割はスキップ）',
      '  フェードアニメーション 200ms を追加',
      '  ローテーション位置インジケーター（ドット）を追加',
      '',
      '【I-3】実況ログ + vs表示の改善',
      '  実況ログから「投手→打者:」の記述を削除（打者名+投球詳細のみ）',
      '  ストライクゾーン上の vs表示を2行形式に変更',
      '  投手：○○(学校) / 打者：○○(学校) の2行表示',
    ],
  },
  {
    version: '0.27.0',
    date: '2026-04-22',
    changes: [
      '⚾ Phase 12-H: 試合開始演出＋自動進行機能',
      '【H-1】PLAY BALL 演出オーバーレイ',
      '  試合新規開始時に画面中央へ半透明白帯 + 太字 "PLAY BALL" をフェードイン/アウト',
      '  フェードイン 300ms → 2秒静止 → フェードアウト 500ms (総 2.8 秒)',
      '  エンジ系ボーダーラインをアクセントとして追加',
      '  中断→再開では表示しない（新規開始のみ）',
      '',
      '【H-2】TimeMode を 3段階に拡張',
      '  旧: short | standard → 新: slow(10秒) | standard(5秒) | fast(3秒)',
      '  runner-types.ts の TimeMode 型を更新',
      '  既存テストを fast (旧 short 相当) に置き換え',
      '',
      '【H-3】自動進行モード（新規）',
      '  match-store に autoAdvance / pendingNextOrder / nextAutoAdvanceAt を追加',
      '  アクション: setAutoAdvance / setPendingNextOrder / consumeNextOrder',
      '  AutoAdvanceBar コンポーネント: 自動進行トグル + TimeMode 3ボタン + カウントダウン',
      '  カウントダウン表示: 「次の1球まで 残り 3.2秒」（100ms 更新）',
      '  PitchMode = on → stepOnePitch、off → stepOneAtBat を自動実行',
      '  「今すぐ進める」「指示なし」ボタンを提供',
      '',
      '【H-4】停止理由で自動進行を一時中断',
      '  pauseReason が non-null のときタイマーをクリアして待機',
      '  resumeFromPause (pauseReason → null) で自動進行が再開される',
      '',
      'テスト: phase12h.test.ts 追加 — 16 件',
      '  TimeMode 型チェック、DELAY_MS マッピング、autoAdvance 状態遷移、consumeNextOrder',
    ],
  },
  {
    version: '0.25.0',
    date: '2026-04-22',
    changes: [
      '🎨 Phase 12-G: 試合画面ビジュアル リファイン',
      '【G-1】グラウンド・ストライクゾーン 40% 縮小',
      '  Ballpark.module.css: max-width 450px → 270px',
      '  StrikeZone.module.css: max-width 300px → 180px',
      '  match-visual.module.css: 2カラム → 3カラム（グラウンド・ゾーン・情報パネル）',
      '  実況ログ・心理ウィンドウを右カラムへ移動、縮小分のスペースを有効活用',
      '',
      '【G-2a】ホームラン = 場外まで飛ぶアニメーション',
      '  computeTrajectory: ホームラン(≥350ft)の endPos を 2.8 倍に拡大 → Canvas 外へ消える',
      '',
      '【G-2b】内野ゴロ = 守備→送球→走塁 プレイシーケンス',
      '  useBallAnimation.ts に PlaySequence/PlayPhase/PlaySequenceState 型を追加',
      '  buildGroundOutSequence(): ゴロ方向から守備位置を判定し5フェーズシーケンスを構築',
      '  triggerPlaySequence(): RAF ループで各フェーズを順次アニメーション',
      '  BallparkCanvas.ts: drawBatterRunner() / drawResultFlash() 追加',
      '  フィールダーマーカーがボールに向かって移動 → キャッチ → 一塁送球',
      '  同時にバッターが一塁へ走塁（黄色マーカー）',
      '  一塁での判定「アウト！/セーフ！」フラッシュ表示',
      '',
      '【G-3】ストライクゾーン = 投球軌道アニメーション',
      '  StrikeZone.tsx に computePitchTrajPos() 追加',
      '  投球開始時に白い ◯ がゾーン上部に出現 → 着弾点まで 380ms で移動',
      '  変化球: breakDirection に応じて軌道が曲がる（スライダー横・カーブ下・フォーク急落下）',
      '  ストレート高速: わずかにホップ（上方向オフセット）',
      '  アニメーション中は最新マーカーを非表示、着弾後にスケールインで表示',
      '',
      '【G-4】スイング位置マーカー = バット形状',
      '  SwingMarkerSvg: 18×10 の小矩形 → バット形状（台形＋バレル端円、-25°アッパースイング）',
      '  グリップ側細く・バレル側太い台形で視覚的にバットと認識できる形状',
      '',
      '  テスト: 22 件追加（buildGroundOutSequence・computePitchTrajPos・ホームラン距離）',
      '  field-coordinates.test.ts: Phase 12-F 座標変更に合わせてテストを更新（3件修正）',
    ],
  },
  {
    version: '0.24.1',
    date: '2026-04-22',
    changes: [
      '🐛 [バグ修正] 試合中の盗塁指示が反映されない問題を修正',
      '  原因: UI側で走者の「名前」を engine の runnerId として渡していたため、engine 側で照合に失敗し盗塁処理がスキップされていた',
      '  修正: RunnerBaseView に playerId フィールドを追加（projector で埋める）',
      '        SelectPanel の盗塁走者選択で r.playerId を渡すよう変更',
      '  副次改善: 盗塁ランナー選択モーダルに学校短縮名を表示（v0.23.0仕様に合わせる）',
      '',
      '  影響範囲:',
      '    src/ui/projectors/view-state-types.ts — RunnerBaseView に playerId, schoolShortName 追加',
      '    src/ui/projectors/matchProjector.ts — buildBasesView で playerId と shortName を埋める',
      '    src/app/play/match/[matchId]/page.tsx — SelectPanel steal モードで playerId を渡す',
    ],
  },
  {
    version: '0.24.0',
    date: '2026-04-22',
    changes: [
      '⚾ Phase 12: 試合画面ビジュアル化 — 全5サブフェーズ実装',
      '【12-A】アニメーション付きスコアボード: イニング開始時にスライドイン→2秒表示→スライドアウト',
      '  AnimatedScoreboard.tsx + useScoreboardVisibility.ts フック',
      '  イニング別スコア表・アウトカウント・チームスコアをオーバーレイ表示',
      '  prefers-reduced-motion 対応（アニメーション省略）',
      '  MatchHUD: 常時表示のコンパクトHUD (B/S/O・イニング・スコア)',
      '  StrikeZone.tsx: SVG製ストライクゾーンの骨格',
      '【12-B】ストライクゾーンマーカー: ◯（速球）/ △（変化球）マーカー表示',
      '  pitch-marker-types.ts: PitchMarker / SwingMarker / AtBatMarkerHistory 型',
      '  pitchLocationToUV(): 5×5エンジングリッド → UV座標',
      '  getBreakDirection(): 変化方向ベクトル（左右投手で dx 反転）',
      '  match-visual-store.ts: Zustandストア（打席間マーカー管理）',
      '  CircleMarker / TriangleMarker / SwingMarkerSvg — CSS scale-in アニメーション',
      '【12-C】グラウンド鳥瞰 Canvas: 球場・選手・ランナー描画',
      '  field-coordinates.ts: フィールド座標系 ↔ Canvas座標系変換',
      '  FIELD_POSITIONS: 全9ポジション + ベースの座標定義',
      '  BallparkCanvas.ts: 純粋関数で Canvas 2D 描画（スタンド/外野/内野/ダイヤモンド/選手）',
      '  Ballpark.tsx: ResizeObserver で正方形維持・devicePixelRatio 対応',
      '  matchProjector.ts: outs / currentInning / pitcherHand / runnerTeams を追加出力',
      '【12-D】ボール・打球アニメーション: requestAnimationFrame 60fps',
      '  useBallAnimation.ts: triggerPitchAnimation / triggerHitAnimation フック',
      '  bezier2(): 2次ベジェ曲線, pitchSpeedToDuration(): 球速→アニメーション時間',
      '  computeTrajectory(): BatContactForAnimation → BallTrajectory',
      '  打球影: 高さに応じてサイズ・透明度が変化 (drawBallWithShadow)',
      '  match-store.ts: breakDirection / swingLocation / batContact を PitchLogEntry に追加',
      '【12-E】ホームランエフェクト・FPS最適化',
      '  パーティクルエフェクト: 32パーティクル + フラッシュ + 「ホームラン！」テキスト (1.4秒)',
      '  オフスクリーン Canvas キャッシュ: 静的背景をキャッシュしてアニメーション時の描画コスト削減',
      '  FPS 30 上限: requestAnimationFrame にフレームスキップを追加',
      '  triggerHomeRunEffect(): ホームランパーティクルを起動するフック',
      '【テスト】56件の新規ユニットテスト追加',
      '  pitch-marker-types: 16テスト, field-coordinates: 20テスト, useBallAnimation: 20テスト',
      '  合計: 971テスト (915 既存 + 56 新規)',
    ],
  },
  {
    version: '0.23.0',
    date: '2026-04-21',
    changes: [
      '🎭 Phase 11.5: 物語化リデザイン — 全7サブフェーズ実装',
      '🏠 11.5-A: ホーム画面タブUI（自校/他校/評価者）・チーム状態サマリー',
      '⚾ 11.5-B: チーム画面に今日の練習設定セクション追加',
      '📊 11.5-C: 評価者システム基盤（24評価者・ランク計算エンジン）',
      '📝 11.5-D: 選手能力値の言葉化（13能力×7段階×2+候補）',
      '👤 11.5-E: 選手プロフィール拡充（今の気持ち・練習履歴・イベント履歴）',
      '🔍 11.5-F: マネージャー経由スカウティングレポート言葉化',
      '👩‍💼 11.5-G: マネージャー管理画面（/play/staff・複数雇用・育成）',
    ],
  },
  {
    version: '0.22.0',
    date: '2026-04-20',
    changes: [
      '🔧 Phase 7-F: 細かい修正5件',
      '【1】試合画面から詳細画面へ遷移 — 高校名・選手名クリックで飛べる',
      '  詳細画面に「試合に戻る」ボタン (sessionStorage で matchId 保持)',
      '【2】学校名の3文字短縮表記 — 例「新潟県立長岡商業高等学校」→「長岡商」',
      '  generateShortName() を school-generator.ts に実装',
      '  既存セーブデータは world-store.ts で自動 migration',
      '  選手名の横に (短縮名) を表示して攻撃側・守備側を識別可能に',
      '【3】采配の前回選択継続 — 「前回と同じ」ボタン追加',
      '  match-store.ts に lastOrder state 追加',
      '  打者が変わると自動リセット',
      '【4】盗塁の完全実装 — attemptSteal() を実装、実況ログに表示',
      '  ランナー速度 vs 捕手肩力で成功判定',
      '  「○○、二塁へ盗塁成功！」「△△、二塁盗塁失敗！タッチアウト」',
      '  新規テスト tests/engine/match/steal.test.ts (368行)',
      '【5】アウトの詳細化 — ゴロ/フライ/三振/守備位置を明記',
      '  「サード正面のゴロ、ファースト送球アウト」',
      '  「センターフライ、アウト」',
      '  「空振り三振」「見逃し三振」',
    ],
  },
  {
    version: '0.21.0',
    date: '2026-04-20',
    changes: [
      '🧠 Phase 7-E: 心理システム仕上げ — モノローグが試合に効く',
      '【7-E1】MentalEffect → MatchOverrides → 試合ロジック反映:',
      '  MatchOverrides インターフェース追加 (runner-types.ts)',
      '  runner.stepOnePitch/stepOneAtBat に overrides?: MatchOverrides を追加',
      '  getEffectiveBatterParams / getEffectivePitcherParams が補正を受け取る',
      '  contactBonus / powerBonus / swingAggressionBonus / velocityBonus / controlBonus',
      '  補正係数クリップ: ±0.3（velocity は ±5km/h）',
      '  buildBatterOverridesFromEffects / buildPitcherOverridesFromEffects ヘルパー追加',
      '【7-E2】ignoreOrder 実装（頑固特性）:',
      '  hasIgnoreOrderEffect() で MentalEffect 配列を検査',
      '  stubborn 特性のモノローグが発火すると采配を即時リセット',
      '  実況ログに「[名前]は監督の指示を無視した！」を追加',
      '【7-E3】モノローグ連続重複回避:',
      '  generatePitchMonologues(ctx, excludeIds?) — 除外セット引数追加',
      '  match-store.ts に recentMonologueIds: string[] を追加（最新5件リングバッファ）',
      '  PitchMonologuesWithEffects: pickedIds フィールド追加',
      '【7-E4】新特性10種の選手生成への割り当て:',
      '  generateTraits(rng, position?) — 位置引数追加（後方互換）',
      '  中頻度特性プール: hotblooded/stoic/cautious/scatterbrained/steady/timid（各~7.5%）',
      '  希少特性: clutch_hitter/big_game_player（~2%、野手）、ace（~2%、投手のみ）',
      '  stubborn（~1%、全ポジション）',
      '  新コンフリクト: hotblooded↔stoic、cautious↔timid、hotblooded↔cautious、stoic↔scatterbrained',
      '【テスト】tests/engine/psyche/phase7e.test.ts 追加 — 26テスト',
      '  合計: 843テスト (817 既存 + 26 新規)',
    ],
  },
  {
    version: '0.20.0',
    date: '2026-04-20',
    changes: [
      '🧠 Phase 7-B/C/D: 心理システム・細かい采配・特性拡張',
      '【7-B】心理システム基盤:',
      '  src/engine/psyche/types.ts — MonologuePattern / MentalEffect / PitchContext 型定義',
      '  src/engine/psyche/monologue-db.ts — 45パターンのモノローグDB（設計書§10 20件含む）',
      '  src/engine/psyche/generator.ts — generatePitchMonologues() 実装（状況/特性/采配マッチング）',
      '  PitchLogEntry に monologues?: MonologueEntry[] フィールド追加（optional: 後方互換）',
      '  match-store.ts に generatePitchMonologues() 統合 — stepOnePitch/stepOneAtBat で生成',
      '  PsycheWindow.tsx — 試合画面に心理ウィンドウUI追加（打者左・投手右・捕手中央の吹き出し）',
      '【7-C】細かい采配:',
      '  TacticalOrder に BatterDetailedOrder / PitcherDetailedOrder を追加',
      '  DetailedOrderModal.tsx — 「⚙ 細かく指示」ボタン + コース/球種/積極性 選択モーダル',
      '  match-store.ts: currentOrder フィールド追加、toOrderConditionType() でモノローグと連動',
      '  §5 効果メカニズム: 采配タイプ → OrderConditionType 変換でモノローグ生成に反映',
      '【7-D】特性拡張（10種追加）:',
      '  TraitId に hotblooded / stoic / cautious / stubborn / clutch_hitter / scatterbrained',
      '             / big_game_player / steady / timid / ace を追加',
      '  TRAIT_LABELS に日本語マッピング追加',
      '  モノローグDB に新特性対応パターン追加（大舞台/ビビリ×甲子園 等）',
    ],
  },
  {
    version: '0.19.0',
    date: '2026-04-19',
    changes: [
      '⚾ Phase 7-A: 1球モード基盤実装',
      '【7-A-1】デフォルト1球モード: 新ゲーム開始時に pitch: on がデフォルト',
      '  既存セーブデータとの互換性維持（旧データは pitch: on にフォールバック）',
      '  PitchLogEntry に pitchSpeed / pitchLocation / pitchTypeLabel を追加（optional）',
      '【7-A-2】実況ログ詳細化: 球速(km/h)・コース・球種を実況文に組み込み',
      '  例: 「⚾ 鈴木 → 田中: 内角低めのスライダー 138km/h … 空振り」',
      '  投手の velocity 能力値から km/h を自動計算',
      '【7-A-3】実況ログ アコーディオンUI',
      '  通常: 1行表示（最大48文字 + ▼ アイコン）',
      '  クリック/タップで全文展開（▲ で折りたたみ）',
      '  最新10件表示、11件目以降は「もっと見る（N件）」ボタンで展開',
    ],
  },
  {
    version: '0.18.5',
    date: '2026-04-19',
    changes: [
      '🔧 Phase 7-A: 基盤整備（1球モードデフォルト化 WIP）',
      '【デフォルト変更】runnerMode デフォルトを pitch: off → on に',
      '  新規試合は1球ごと停止がデフォルト（プレイヤーが任意に切り替え可能）',
      '【MatchState 拡張】runnerMode? フィールド追加',
      '  既存セーブデータとの互換性維持（undefined は on にフォールバック）',
      '【次のステップ】実況ログ詳細化 + アコーディオン化',
    ],
  },
  {
    version: '0.18.4',
    date: '2026-04-19',
    changes: [
      '🔧 Phase 11-D: 磨き込み第1弾',
      '【バグ修正】A1 個別練習メニュー — パラメータが見える化 (小数第1位表示)',
      '【成長速度改善】練習成長を 1.5-2倍に引き上げ (baseGain 0.3→0.5 等)',
      '  1週間の集中メニューで +5-8 の成長が見えるように',
      '【A2 リセット】監督戦術スタイル (旧A2) を revert',
      '  新A2「細かい采配＋選手心理描写」への再設計開始',
      '  DESIGN-PHASE11-A2-NEW.md に新構想を記載',
    ],
  },
  {
    version: '0.18.3',
    date: '2026-04-19',
    changes: [
      '🎓 Phase 11-A4: OB表示 (MVP)',
      'ホーム画面に「最近のOB」カード追加',
      '直近3年以内の卒業生から総合力上位3名を表示',
      'プロ入り選手は⭐マークとゴールド背景で強調',
    ],
  },
  {
    version: '0.18.2',
    date: '2026-04-19',
    changes: [
      'Phase 11-A3: 選手モチベーションシステム',
      'Player に motivation フィールド追加 (0-100, デフォルト50, 後方互換)',
      '試合出場 +5、ホームラン +3、好投 +5、ベンチ -2、休養日 +3',
      'ライバル多い (同ポジション3人以上) -1/日、疲労80以上 -3/日',
      '試合パフォーマンス: motivation ≥70 で +10%、≤30 で -10%',
      '練習効率: motivation ≥70 で +20%、≤30 で -20%',
      'チーム画面に「やる気」列 (🔥 / 😢 アイコン付き)',
      '選手詳細画面にモチベーションバー表示',
    ],
  },
  {
    version: '0.18.1',
    date: '2026-04-19',
    changes: [
      'Phase 11-A2: 監督戦術スタイル (aggressive/balanced/defensive/small_ball)',
      '監督に style フィールドを追加（optional、後方互換）',
      'aggressive: 長打係数+5%、CPU バント/盗塁確率-10%',
      'defensive: エラー率-10%、CPU 送りバント+10%',
      'small_ball: CPU 送りバント+25%、盗塁成功率+5%',
      'チーム画面の監督セクションに戦術スタイルドロップダウンを追加',
      'worldStore.setManagerStyle() アクション追加',
    ],
  },
  {
    version: '0.18.0',
    date: '2026-04-19',
    changes: [
      '📘 Phase 11 開幕 — プレイ体験の深化',
      '🎯 個別練習メニュー (Issue #4): 選手ごとに異なる練習を割り当て可能',
      'チーム画面に「個別練習」列とドロップダウン追加',
      '個別メニュー未設定なら従来通りチーム共通メニュー',
      'Phase 11-A1 対応',
    ],
  },
  {
    version: '0.17.0',
    date: '2026-04-19',
    changes: [
      '⏸ 試合中断/再開機能 (Issue #8)',
      '試合画面に「⏸ 中断してホームへ」ボタン',
      'ホーム画面に「⚾ 試合再開」バナー',
      '試合状態・実況ログ・投球ログを JSON で保存',
      'MatchState Map/Set serialize + round-trip 復元',
      'Issue #8 (PR #6) 対応',
    ],
  },
  {
    version: '0.16.0',
    date: '2026-04-19',
    changes: [
      '🏠 ホーム画面にチーム状況サマリー追加 (Issue #3 MVP)',
      '  - 負傷中選手・けが注意選手・好調選手を一覧表示',
      '  - 休養中マーカー🛌',
      '  - チーム画面への一括休養リンク',
      'Issue #3 (PR #5) MVP 対応',
    ],
  },
  {
    version: '0.15.0',
    date: '2026-04-19',
    changes: [
      '📊 通算成績が記録されるように (Issue #6)',
      '試合終了後に自動で選手の careerStats に加算',
      'シーズン別成績 (1年/2年/3年) を選手詳細画面に表示',
      'Issue #6 (PR #4) 対応',
    ],
  },
  {
    version: '0.14.0',
    date: '2026-04-19',
    changes: [
      '🛌 けが人・けが注意を一括休養ボタン (チーム画面)',
      '休養選手は翌日まで能力変化なし、疲労を大幅回復',
      '翌日の日次処理で自動的に通常練習に復帰',
      '選手一覧に休養中マーカー🛌を表示',
      'Issue #5 (PR #3) 対応',
    ],
  },
  {
    version: '0.13.2',
    date: '2026-04-19',
    changes: [
      '進行ボタン (1球/1打席/1イニング/最後まで) を自動進行バーに統合',
      '進行ボタン+自動進行+速度を1行にまとめて大幅省スペース化',
      '下部にあった大きな進行カードを削除',
    ],
  },
  {
    version: '0.13.1',
    date: '2026-04-19',
    changes: [
      '🎯 采配バナーとボタンを統合: 画面を上下移動せずに采配できるように',
      '「打席開始 — 采配サインを送ってください」等のバナーを采配カード上部に表示',
      '下のバナー + 上の采配ボタン往復ストレスを解消',
    ],
  },
  {
    version: '0.13.0',
    date: '2026-04-19',
    changes: [
      '🎨 共通ヘッダー (GlobalHeader) を新設、全画面で高さ固定 (desktop 56px / mobile 48px)',
      '🎨 セーブ/ロード/メニューをアイコンボタン化、ハンバーガーメニューで画面遷移',
      '🎨 各画面の独自ヘッダーを細いサブバーに変更、二重ヘッダーを解消',
      '🎨 試合画面: 実況ログをスコアボード直下に移動 (リアルタイム感向上)',
      '🎨 試合画面: 自動進行UIをアイコンのみにコンパクト化',
      'Issue #2 / #9 / #10 対応',
    ],
  },
  {
    version: '0.12.7',
    date: '2026-04-19',
    changes: [
      '🔴 リロードで学校選択画面に戻るバグを修正',
      'Zustand persist の hydration 完了前に /new-game へリダイレクトしていた',
      '_hasHydrated フラグを追加、UI は復元完了を待ってから判断',
      '試合画面 (/play/match/[matchId]) も同様に修正',
    ],
  },
  {
    version: '0.12.6',
    date: '2026-04-19',
    changes: [
      '実況ログから内部用語「インプレー」を除去',
      'ホームラン/ヒット/二塁打/三塁打/アウト等を球種と同じ行で直接表示',
      '例: 「石川 → 吉川: チェンジアップ … 🔥 ホームラン！！」',
      '得点発生時は「⚾ N点追加！」を続けて表示',
    ],
  },
  {
    version: '0.12.5',
    date: '2026-04-19',
    changes: [
      'スコアボード: 無得点イニングでも 0 が表示されるように修正',
      '投手が stats.pitching=null の選手に設定されて試合が止まるバグを修正',
      '投手が見つからない場合は緊急用の pitching stats で試合を継続',
      'テスト追加: 全イニング完走後に inningScores が全て数値で埋まること',
    ],
  },
  {
    version: '0.12.4',
    date: '2026-04-19',
    changes: [
      '🔴 重大: 2ストライクで三振してしまうバグを修正',
      '原因: ホームランやヒットの後、打席終了時のカウントがリセットされず、次の打者に前の打席のストライク数が引き継がれていた',
      'processAtBat インプレー break 時に count リセットを追加',
      'runner.stepOneAtBat に count リセットの防衛コードを追加',
      'テスト追加: 打席終了後の count=0-0 を検証（修正前は再現失敗）',
    ],
  },
  {
    version: '0.12.3',
    date: '2026-04-19',
    changes: [
      '実況ログ改善: 1球モードでも「🧢 N番打者 登場」を表示（打席開始が分かるように）',
      '実況ログ改善: インプレー時にヒット/アウトなどの結果を1球モードでも明示',
      '実況ログ改善: 「投球 N球」を「N番打者 vs 投手（N球）」形式にまとめた',
      'テスト追加: stepOnePitch 単独で試合完走することを検証',
      'テスト追加: stepOneAtBat → stepOnePitch の混合進行でも打者が解決できることを検証',
    ],
  },
  {
    version: '0.12.2',
    date: '2026-04-19',
    changes: [
      '「打者 不明」で試合が止まるバグを修正（battingOrder の整合性を保証）',
      'buildMatchTeam に整合性チェック＋フォールバックを追加',
      '試合完走テスト（複数シード × 150打席）を追加、全558テスト全パス',
    ],
  },
  {
    version: '0.12.1',
    date: '2026-04-19',
    changes: [
      '打席後に同じ打者が再登場するバグを修正（打順 +1 が漏れていた）',
      '自動進行ON中は手動ボタンを無効化（2打席進んでしまう問題を解消）',
      '自動進行中に手動操作しようとすると注意メッセージを表示',
    ],
  },
  {
    version: '0.12.0',
    date: '2026-04-19',
    changes: [
      '🔴 データ永続化: Redis 連携を追加（MemoryKV 問題を根本解決）',
      'pm2 restart でもユーザーアカウント・セーブデータが消えなくなった',
      'ecosystem.config.js + .env でプロセス管理を整備',
      'deploy.sh が .env を source して pm2 に環境変数を注入',
      '※ 過去に登録していたアカウントは消失のため、再登録が必要です',
    ],
  },
  {
    version: '0.11.1',
    date: '2026-04-19',
    changes: [
      '試合が途中で止まるバグを修正（3アウト時に攻守交代が走らないケース）',
      '打席進行時の打順二重進行バグを修正（processAtBat と runner の両方で +1 していた）',
      '3アウト・チェンジを実況ログで大きく表示',
      'アウト加算時にナレーション出力を追加',
      '試合終了時に「ゲームセット！」と明示',
    ],
  },
  {
    version: '0.11.0',
    date: '2026-04-19',
    changes: [
      '全画面にバージョン表示バッジを追加（右下に固定表示）',
      'クリックで変更履歴ポップアップを表示',
    ],
  },
  {
    version: '0.10.3',
    date: '2026-04-19',
    changes: [
      '秋大会起動バグを修正（activeTournament 残留クリーンアップ）',
      '既存セーブデータの自動マイグレーションを追加',
    ],
  },
  {
    version: '0.10.2',
    date: '2026-04-19',
    changes: [
      'Phase 10-B: 自動進行と実況テキスト表示',
      'ホーム戻り時のタイトル画面遷移バグ修正',
    ],
  },
  {
    version: '0.10.1',
    date: '2026-04-18',
    changes: [
      'Phase 10-B: 1球単位でも野球が成立（三振・四球・攻守交代の即時処理）',
      '本番ビルド修復（import path と型ミスマッチ解消）',
    ],
  },
  {
    version: '0.10.0',
    date: '2026-04-18',
    changes: [
      'Phase 10-B/C: インタラクティブ試合UI + 大会統合',
      'Phase 5.5: 大会試合を quickGame 実シミュに置き換え',
      'Phase 10-A: applyPinchRun / applyDefensiveSub 実装',
      'Phase 5-B: 練習試合・紅白戦システムを実装',
      '大会終了後の season phase 誤表示バグを修正',
    ],
  },
];
